apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: financial-contract-activated
  x-event: Contrato Financeiro Ativado
  description: Evento disparado quando um contrato financeiro é ativado
  tags:
    - kafka
    - asyncapi
spec:
  type: asyncapi
  lifecycle: experimental
  owner: coe-integracoes
  definition:
    asyncapi:
      $text: ./asyncapi/financial-contract-activated.yaml
    schemas:
      value:
        $text: ./schemas/financial-contract-activated-value.avsc
      key:
        $text: ./schemas/financial-contract-activated-key.avsc

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: financial-contract-activated-processed
  x-event: Contrato Financeiro Ativado Processado
  description: Evento que representa o retorno do processamento da ativação de contrato financeiro.
  tags:
    - kafka
    - asyncapi
spec:
  type: asyncapi
  lifecycle: experimental
  owner: coe-integracoes
  definition:
    $text: ./asyncapi/financial-contract-activated-processed.yaml
  x-avro:
    value:
      $text: ./schemas/financial-contract-activated-processed-value.avsc
    key:
      $text: ./schemas/financial-contract-activated-processed-key.avsc
