DEV:
  config:
    cleanup.policy: delete
    confluent.key.schema.validation: 'true'
    confluent.key.subject.name.strategy: io.confluent.kafka.serializers.subject.TopicNameStrategy
    confluent.value.schema.validation: 'true'
    confluent.value.subject.name.strategy: io.confluent.kafka.serializers.subject.TopicNameStrategy
    delete.retention.ms: '86400000'
    max.compaction.lag.ms: '9223372036854775807'
    max.message.bytes: '20971520'
    message.timestamp.after.max.ms: '9223372036854775807'
    message.timestamp.before.max.ms: '9223372036854775807'
    message.timestamp.difference.max.ms: '9223372036854775807'
    message.timestamp.type: CreateTime
    min.compaction.lag.ms: '0'
    min.insync.replicas: '2'
    retention.bytes: '-1'
    retention.ms: '604800000'
    segment.bytes: '104857600'
    segment.ms: '604800000'
  partitions_count: 3
HML: &ref_0
  config: {}
  partitions_count: 3
PRD: *ref_0
